### ISSUE TITLE
Fetch an old release

### ISSUE THREAD

**Issue by Manifaust** [pivotal-cf-experimental/pivnet-resource#13]
Currently there's no way to fetch files from an old release. My use case is that I want my pipeline to test upgrading from an old tile to a new tile. There's no way to download the old tile with a pivnet-resource. Something similar to this would work for me:

```
- get: p-app-distribution
  params:
    product_version: 1.2.5
    globs:
      - "*p-app-distribution*"
```

**Comment by robdimsdale** [comment]
@Manifaust this makes sense. I think the configuration should live in the global `source` configuration, rather than the params of the `get`. This is more consistent with other resources (e.g. the [git-resource](https://github.com/concourse/git-resource) and the [s3-resource](https://github.com/concourse/s3-resource)) and fits better into the concourse model of each logical resource mapping to a separate resource in the pipeline config.

I propose it looks as follows:

```
---
resources:
- name: p-app-distribution-1.2.5
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: p-app-distribution
    product_version: 1.2.5

- name: p-app-distribution-latest
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: p-app-distribution

jobs:
- name: upgrade-p-app-distribution
  plan:
  - aggregate:
    - get: p-app-distribution-1.2.5
      params: {globs: ["*p-app-distribution*"]}
    - get: p-app-distribution-latest
      params: {globs: ["*p-app-distribution*"]}
  - task: perform-upgrade
    file: [...]
```

It sounds like the version can be fixed, as opposed to parsing the blobs as semver e.g. `product_version: 1.2.(.*)` - this means that to change the version of the tile you are upgrading from, you would need to reconfigure the pipeline with a new value of `product_version`. It is significantly easier to keep the version fixed than to parse the blobs as semver, so we can start with that.

The following tracker story has been created for this feature - please let us know if you don't think this will meet your requirements.

- [pivnet resource check should support fixing to a specific product version](https://www.pivotaltracker.com/story/show/116034635)

Thanks,
Rob
