### ISSUE TITLE
Pivnet resource out should allow me to specify a Docs URL

### ISSUE THREAD

**Issue by mfine30** [pivotal-cf-experimental/pivnet-resource#17]
We have found another interesting case, where we need the ability to specify a Docs Url. Currently, before posting our product to PivNet, we make a [post](https://network.pivotal.io/docs/api#public/docs/api/v2/product_files.md) to api/v2/product_files so that we can specify custom information, such as file_version, docs_url, and system_requirements. Since this falls into a new endpoint, product_files, please let me know if you want me to create a separate issue or this one is ok. Thus far, it seems like the PivNet resource only supports metadata around `releases`, plus the addition of the information that should happen as a result in #15. This is another unrelated field that we would like to dynamically configure.

Thanks,
Morgan

**Comment by robdimsdale** [comment]
@mfine30 the metadata file currently supports a top-level `product_files` key where you can specify the `name`, the `description`, and `upload_as` to rename file during upload.

It sounds like you want the ability to add the following nested fields to that existing key:

```
---
product_files
- file: /some/path/to/file
  version: some-version
  docs_url: https://some.docs.url
  system_requirements:
  - some_requirement
  - another_requirement
```

Does this meet your requirements?

Thanks,
Rob
