### ISSUE TITLE
Pipeline stuck at 'Waitting for suitable set of input versions' when trying to get ops manager

### ISSUE THREAD

**Issue by bonzofenix** [pivotal-cf-experimental/pivnet-resource#32]
We are trying to use the pivnet-resource to pull an ops manager ova. we provision the resource through resource-types:

```
resource_types:
- name: pivnet
  source:
    insecure_registries:
    - PRIVATE_REGISTY:5000
    repository: PRIVATE_REGISTRY:5000/pivotalcf/pivnet-resource
    tag: latest
  type: docker-image
```

We did check that the image and the tag are in the registry.

we perform the check and the get as it is specified in the docs, still the build does not seem to start:.

Check:

```
- name: ops-manager-ova
  source:
    api_token: **********************
    product_slug: ops-manager
  type: pivnet
```
Get:

```
 - get: ops-manager-ova
    params:
      globs:
      - '*vsphere*'
```

are we missing anything?

@bonzofenix && @cloud-dude

**Comment by robdimsdale** [comment]
Firstly, is the indentation correct? It looks a little off e.g.:

```
 - get: ops-manager-ova
      params:
        globs:
        - '*vsphere*'
```

should be:

```
 - get: ops-manager-ova
    params:
      globs:
      - '*vsphere*'
```

Secondly, what version are you actually running? If you're using the same tags in your private registry as we publish on dockerhub, you should use the tag `latest-final`. In case you're not familiar, in the docker world `latest` does not do what you might expect - it returns the most recent untagged image, which in our case is very old (from before we versioned the resource).
