### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by ebabani** [pivotal-cf-experimental/pivnet-resource#4]
We can't seem to get past this error:

"Failed to Download Files: open /tmp/build/get/light-bosh-stemcell-3146.7-aws-xen-hvm-ubuntu-trusty-go_agent.tgz: no such file or directory"

We've just tried to implement to a simple pipeline based on the stemcells sample code in the readme to try and eliminate the chances that we're just using the resource wrong but we keep hitting that error. Here's the pipeline we're trying with. Any advice is much appreciated.

```
---
##############
# Pivnet     #
##############

resources:
  - name: pivnet-releases
    type: pivnet
    source:
      api_token: *************
      product_slug: stemcells


jobs:
  - name: aws-and-vsphere-stemcells
    plan:
    - get: pivnet-releases
      params:
        globs:
        - "*aws*"
        - "*vsphere*"
    - task: use-it
      config:
        platform: linux
        image: docker:///cfmobile/bosh-release
        run:
          path: /bin/bash
          args: ["-c", "ls pivnet-releases"]
        inputs:
          - name: pivnet-releases
```
