### ISSUE TITLE
No current support for specifying `description`s or `name`s of Pivnet product files

### ISSUE THREAD

**Issue by RochesterinNYC** [pivotal-cf-experimental/pivnet-resource#6]
The `pivnet-resource` will automatically create product files on Pivnet and associate them to the release when creating a release via `put`. It allows the parameter `description_file` that is a file that contains the description for the release. However, no possible parameters are provided that allow the setting of the descriptions or names of the product files.

Our use case as the CF Buildpacks team is that we provide changelog details, a list of the packaged binaries, and the SHA256 of the zipped buildpack in the descriptions of the buildpack product files. Additionally, the name of a buildpack product file on Pivnet is typically something like `PHP Buildpack (offline)` rather than the filename (i.e. `php_buildpack-cached-v4.3.5+1455651584`).

Our use case is singular (our concourse job that currently uploads to Pivnet only has to create and designate the description for one product file per job build), but I imagine that specifying different descriptions and names for each product file would be something that the CI pipelines of other teams might require.

**Comment by robdimsdale** [comment]
@RochesterinNYC yes this isn't currently supported, and I agree any solution should be easily extended to cover multiple files (and future properties). One solution could be to provide a machine-parsable metadata file, probably yaml, that could contain the information about the product files:

```
product_files:
- file: /path/to/file/1
  name: pivnet display name 1
  description: |
    some multi line
    description file
- file: /path/to/file/2
  name: pivnet display name 2
```

Files that exist that do not have an associated entry are treated as they currently are (i.e. no description, file name is the same as the path) and keys that are not present for a file will have their default values taken.

I expect this will be configurable in the resource by:

```
jobs:
- name: create-my-files-with-metadata
  plan:
  - put: my-pivnet-release
    params:
      product_files_metadata_file: /path/to/metadata/file
```
Does this proposal address your requirements? It also enables for multiple, optional, files and as well as future keys, optional and madatory
