### ISSUE TITLE
Check Is Unable to Specify Release Type

### ISSUE THREAD

**Issue by mfine30** [pivotal-cf-experimental/pivnet-resource#7]
For our use case, we want to do a `get` of a stemcell from Pivnet. This pipeline is only for LTS releases of our tile. This means that we only want to bump the stemcell when we need to for a CVE. So, when a new "Security Release" stemcell is published on PivNet we want to trigger our pipeline, but when a "Minor Release", for example, is published, we do not want the pipeline to trigger.

I would envision the resource definition looking something more like
```
resources:
- name: stemcells
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: stemcells
    release_type: security
```

**Comment by robdimsdale** [comment]
@mfine30 this makes sense. Ideally I'd prefer to see all products support semver, then we could solve this sort of problem by introducing regex that we would parse as semver e.g.:

```
resources:
- name: stemcell-1.9.x
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: stemcells
    release_semver: 1.9.(.*)
```

However, given that not all products are semantically-versioned (stemcells being a great example) then I don't see a better way to achieve this goal than your suggestion.

I'll keep this issue open until there's some stories in the [tracker backlog](https://www.pivotaltracker.com/projects/1474244) to cover this, and I'll link to them in here and close this issue at that time.

Thanks.
