### ISSUE TITLE
Product should able to declare dependency

### ISSUE THREAD

**Issue by mfine30** [pivotal-cf-experimental/pivnet-resource#8]
As a tile author, my product depends on a specific version of a stemcell. During the upload of my product for a patch release, I would like to be able to specify the type and version of another product that my product depends upon. For example, I should be able to specify that version a.b.c of my tile depends on stemcell 3146.9. Because this second part is dynamic I would imagine that I specify a file path where I can list my dependency(ies?). 

This means that the pivnet resource will have to do a mapping between the version of the dependent product that I care about and the pivnet backing `release_id`. 

https://network.pivotal.io/docs/api#public/docs/api/v2/release_dependencies.md

```
plan: 
- get: pivnet-stemcell
task: bump-stemcell-in-tile
config: some-config
- put: p-tile
    params:
      version_file: some-metadata-files/version
      release_type_file: some-metadata-files/release_type
      eula_slug_file: some-metadata-files/eula_slug
      file_glob: some-source-files/*
      s3_filepath_prefix: P-Gitlab
      dependent_product: stemcell
      dependent_product_version: pivnet-stemcell/version
```

**Comment by robdimsdale** [comment]
@mfine30 this makes sense. It sounds like you have a dependency only on one product, stemcells, but in general any solution to this problem that we implement should support multiple dependencies.

Given that, what does the config look like for multiple dependencies? How do we match the (dynamic) versions with the (not necessarily) static products? We could make `dependent_product: foo` instead an array type `dependent_products: [foo,bar]` but then how do we match each product to their respective `versions`?

I think this would be better solved by configuring the pivnet-resource with some sort of dynamically-generated `metadata` file, contents of which might look something like:

```
dependent_products:
- name: stemcells
  version: 3169.3
- name: some-other-product-slug
  version: some-other-product-version
```

I expect that the build plan (i.e. pipeline config) might then look like:

```
plan: 
- get: pivnet-stemcell
- task: bump-stemcell-in-tile
  config: some-config
- task: write-metadata-file
  file: /path/to/task.yml
- put: p-tile
    params:
      version_file: some-metadata-files/version
      release_type_file: some-metadata-files/release_type
      eula_slug_file: some-metadata-files/eula_slug
      file_glob: some-source-files/*
      s3_filepath_prefix: P-Gitlab
      metadata_file: write-metadata-file-output-dir/metadata.yml
```

I get that this is more work, especially in the single-product case, as now you will need to write this yaml file in a custom task, instead of pointing to existing files on disk. I think this solution scales better.

What do you think? If this feature were implemented as described above, would it meet your requirements?

Thanks,
Rob
